import React from 'react';
import { Sparkles, BarChart, Table as TableIcon, Activity, Plus, Maximize2, RefreshCw } from 'lucide-react';

interface GenerativeWidgetProps {
    type: 'chart' | 'table' | 'kpi' | 'suggested_action';
    data: any;
    title: string;
}

export default function GenerativeWidget({ type, data, title }: GenerativeWidgetProps) {
    return (
        <div className="bg-bg-1 border border-stroke rounded-3xl p-6 flex flex-col gap-5 shadow-xl hover:border-ai-accent/30 transition-all group relative overflow-hidden">

            {/* AI Pulse Background */}
            <div className="absolute top-0 right-0 w-32 h-32 bg-ai-accent/5 blur-3xl opacity-0 group-hover:opacity-100 transition-opacity"></div>

            <div className="flex items-center justify-between relative z-10">
                <div className="flex items-center gap-3">
                    <div className="w-8 h-8 rounded-xl bg-ai-accent/10 border border-ai-accent/20 flex items-center justify-center text-ai-accent shadow-lg shadow-ai-accent/10">
                        <Sparkles size={16} fill="currentColor" />
                    </div>
                    <span className="text-[10px] font-black text-white uppercase tracking-widest">{title}</span>
                </div>
                <div className="flex items-center gap-2">
                    <button className="p-1.5 text-text-3 hover:text-white transition-colors"><RefreshCw size={12} /></button>
                    <button className="p-1.5 text-text-3 hover:text-white transition-colors"><Maximize2 size={12} /></button>
                </div>
            </div>

            <div className="flex-1 min-h-[120px] flex items-center justify-center bg-bg-0 border border-stroke rounded-2xl p-4 relative overflow-hidden">
                {type === 'chart' && (
                    <div className="w-full flex flex-col gap-4">
                        <div className="flex items-end gap-2 h-20 items-end justify-around">
                            {[40, 70, 50, 90, 60, 85].map((h, i) => (
                                <div key={i} className="w-4 bg-ai-accent/20 rounded-t-sm relative group/bar" style={{ height: `${h}%` }}>
                                    <div className="absolute inset-0 bg-ai-accent opacity-0 group-hover/bar:opacity-100 transition-opacity"></div>
                                </div>
                            ))}
                        </div>
                    </div>
                )}

                {type === 'kpi' && (
                    <div className="flex flex-col items-center gap-1">
                        <span className="text-3xl font-black text-white tracking-tighter">{data.value}</span>
                        <span className="text-[9px] font-bold text-success uppercase tracking-widest">{data.trend}</span>
                    </div>
                )}

                {type === 'suggested_action' && (
                    <div className="flex flex-col gap-3 w-full">
                        <p className="text-[11px] text-text-2 font-medium italic">"Jarvis detectou que este cliente tem alta propensão a converter um contrato anual."</p>
                        <button className="w-full py-2.5 bg-ai-accent text-white rounded-xl text-[10px] font-black uppercase tracking-widest shadow-lg shadow-ai-accent/20">
                            ENVIAR PROPOSTA ANUAL
                        </button>
                    </div>
                )}
            </div>

            <div className="flex items-center justify-between pt-2 border-t border-stroke/50">
                <span className="text-[8px] font-black text-text-3 uppercase tracking-tighter">Generated by Pulse Visionary v1.0</span>
                <div className="flex -space-x-1">
                    <div className="w-4 h-4 rounded-full bg-ai-accent border border-bg-1 flex items-center justify-center text-[6px] text-white font-bold">J</div>
                </div>
            </div>

        </div>
    );
}
